package ar.edu.untref.aydoo;

/**
 * Created by gabriel on 25/03/17.
 */
public enum Provincia {
    CAPITAL_FEDERAL,BUENOS_AIRES,SANTA_FE,CORDOBA,ENTRE_RIOS,CORRIENTES,MISIONES,CHACO,FORMOSA,
    SALTA,JUJUY,TUCUMAN,CATAMARCA,LA_RIOJA,SANTIAGO_DEL_ESTERO,SAN_JUAN,MENDOZA,SAN_LUIS,LA_PAMPA,RIO_NEGRO,
    NEUQUEN,CHUBUT,SANTA_CRUZ,TIERRA_DEL_FUEGO;
}
